---
services:
  db:
    image: postgres:16.10-alpine3.22
    shm_size: 128mb 
    healthcheck:
      test: ['CMD', '/usr/local/bin/pg_isready', '-U', 'postgres']
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 20s
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db-data:/var/lib/postgres/data
      - ./services/database:/docker-entrypoint-initdb.d/
    networks:
      - microservice_app_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager 
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 20s

  mq:
    image: rabbitmq:4.2.0-rc.1
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 20s
    volumes:
      - mq-data:/var/lib/rabbitmq
    networks:
      - microservice_app_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager 
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 20s

  nginx:
    image: nginx:1.29.3-alpine
    depends_on:
      - gateway
      - session
      - booking
    healthcheck:
      test: ["CMD", "wget", "--spider", "127.0.0.1:8081"]
      interval: 10s
      timeout: 5s
      start_period: 360s
      retries: 3
    volumes:
      - ./services/nginx/gateway_session_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - target: 8081 #  session port
        published: 8081
        protocol: tcp
        mode: host 
      - target: 8087 #  gateway port
        published: 8087
        protocol: tcp
        mode: host 
    networks:
      - microservice_app_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager 
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 20s

  booking:
    image: mksmsh/gertiegr_microservice_app-booking:alpine-1.3
    depends_on:
      - db
      - mq
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:8083"]
      interval: 10s
      timeout: 5s
      start_period: 360s
      retries: 3
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER : postgres
      POSTGRES_DB: reservations_db
      RABBIT_MQ_HOST: mq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
      WAIT_SEC: 60
    secrets:
      - db_password
      - mq_password
    networks:
      - microservice_app_network
    deploy:
      replicas: 2
      mode: replicated
      placement:
        constraints:
          - node.role == worker 
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 20s

  gateway:
    image: mksmsh/gertiegr_microservice_app-gateway:alpine-1.3
    depends_on:
      - db
      - mq
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:8087"]
      interval: 10s
      timeout: 5s
      start_period: 360s
      retries: 3
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SESSION_SERVICE_HOST: session
      SESSION_SERVICE_PORT: 8081
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      BOOKING_SERVICE_HOST: booking
      BOOKING_SERVICE_PORT: 8083
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
      REPORT_SERVICE_HOST: report
      REPORT_SERVICE_PORT: 8086
      WAIT_SEC: 60
    networks:
      - microservice_app_network
    deploy:
      replicas: 2
      mode: replicated
      placement:
        constraints:
          - node.role == worker 
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 20s

  hotel:
    image: mksmsh/gertiegr_microservice_app-hotel:alpine-1.3
    depends_on:
      - db
      - mq
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:8082"]
      interval: 10s
      timeout: 5s
      start_period: 360s
      retries: 3
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: hotels_db
      WAIT_SEC: 60
    secrets:
      - db_password
    networks:
      - microservice_app_network
    deploy:
      replicas: 2
      mode: replicated
      placement:
        constraints:
          - node.role == worker 
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 20s

  loyalty:
    image: mksmsh/gertiegr_microservice_app-loyalty:alpine-1.3
    depends_on:
      - db
      - mq
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:8085"]
      interval: 10s
      timeout: 5s
      start_period: 360s
      retries: 3
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: balances_db
      WAIT_SEC: 60
    secrets:
      - db_password
    networks:
      - microservice_app_network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker 
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 20s

  payment:
    image: mksmsh/gertiegr_microservice_app-payment:alpine-1.3
    depends_on:
      - db
      - mq
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:8084"]
      interval: 10s
      timeout: 5s
      start_period: 360s
      retries: 3
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: payments_db
      WAIT_SEC: 60
    secrets:
      - db_password
    networks:
      - microservice_app_network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker 
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 20s

  report:
    image: mksmsh/gertiegr_microservice_app-report:alpine-1.3
    depends_on:
      - db
      - mq
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:8086"]
      interval: 10s
      timeout: 5s
      start_period: 360s
      retries: 3
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: statistics_db
      RABBIT_MQ_HOST: mq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange 
      WAIT_SEC: 60
    secrets:
      - db_password
      - mq_password
    networks:
      - microservice_app_network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker 
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 20s

  session:
    image: mksmsh/gertiegr_microservice_app-session:alpine-1.3
    depends_on:
      - db
      - mq
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:8081"]
      interval: 10s
      timeout: 5s
      start_period: 360s
      retries: 3
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: users_db
      WAIT_SEC: 60
    secrets:
      - db_password
    networks:
      - microservice_app_network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker 
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 20s

secrets:
  db_password:
    file: ./db.password.example
  mq_password:
    file: ./mq.password.example

volumes:
  db-data:
  mq-data:

networks:
  microservice_app_network:
    driver: overlay
    attachable: true
...
