global:
  resolve_timeout: 1m
  smtp_smarthost: 'smtp.yandex.ru:465'
  smtp_from: '${EMAIL_LOGIN}'
  smtp_auth_username: '${EMAIL_LOGIN}'
  smtp_auth_password: '${EMAIL_PASSWORD}'
  smtp_require_tls: false

route:
  receiver: 'all' 
  group_by:
    - alertname
    - instance
  group_wait: 10s
  group_interval: 10s

receivers:
- name: 'all'
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: '${BOT_TOKEN}'
    chat_id: ${CHAT_ID}
    send_resolved: true
  email_configs:
  - to: '${EMAIL_LOGIN}'
    send_resolved: true
