{
 "title": "Microservice & Monitoring",
 "tags": [
  "docker-swarm",
  "microservice"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Количество нод",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(node_uname_info)" }
   ]
  },
  {
   "title": "Доступность сервисов",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-exporter-http\", instance=\"https://google.com\"}"
    }
   ]
  },
  {
   "title": "Доступная память по нодам",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes) by (instance) / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Занятая память по нодам",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance) / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Количество CPU по нодам",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (instance) (count by (instance, cpu) (node_cpu_seconds_total{mode=\"idle\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Количество стеков",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (container_label_com_docker_stack_namespace)(container_memory_usage_bytes{container_label_com_docker_stack_namespace!=\"\"}))"
    }
   ]
  },
  {
   "title": "Количество контейнеров",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{name!=\"\"})"
    }
   ]
  },
  {
   "title": "Общий CPU по узлам (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU по ядрам каждой ноды (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance, cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}} - ядро {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU по сервисам",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (rate(container_cpu_usage_seconds_total{name!=\"\", container_label_com_docker_stack_namespace=\"microservice\"}[5m])) * 100",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "RAM по сервисам",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 9, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (container_memory_usage_bytes{name!=\"\", container_label_com_docker_stack_namespace=\"microservice\"}) / 1024 / 1024",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Запросы на авторизацию",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{instance=\"session:8081\", method=\"GET\", uri=\"/api/v1/auth/authorize\"})"
    }
   ]
  },
  {
   "title": "Количество бронирований",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_count{exception=\"None\", instance=\"report:8086\", job=\"microservices-micrometer\", method=\"save\", repository=\"BookingStatsRepository\", state=\"SUCCESS\"}"
    }
   ]
  },
  {
   "title": "Запросы Gateway",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{instance=\"gateway:8087\", outcome=\"SUCCESS\"})"
    }
   ]
  },
  {
   "title": "Отправлено RabbitMQ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_exchange_messages_published_total)"
    }
   ]
  },
  {
   "title": "Обработано RabbitMQ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_global_messages_acknowledged_total)"
    }
   ]
  },
  {
   "title": "Логи приложения (Loki)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{stack=\"microservice\"}"
    }
   ]
  }
 ]
}